parent=keycloak
import=common/keycloak

styles=css/styles.css
scripts=js/app.js
locales=it,en

densBackToSelectionUrl=https://dens.dev.numenconsulting.it/loginselector
densShowDemoCredentials=false

densBrandIcon=img/icon-brand.svg
densEmailIcon=img/icon-email.svg
densLockIcon=img/icon-lock.svg


kcFormClass=dens-form
kcFormGroupClass=dens-kc-field
kcLabelClass=dens-label
kcLabelWrapperClass=dens-kc-label-wrap
kcInputWrapperClass=dens-kc-input-wrap
kcInputClass=dens-kc-input
kcInputHelperTextBeforeClass=dens-helper-text dens-helper-text--before
kcInputHelperTextAfterClass=dens-helper-text dens-helper-text--after
kcInputErrorMessageClass=dens-field-error
kcInputGroup=dens-input-wrap
kcFormPasswordVisibilityButtonClass=dens-password-toggle
kcFormGroupHeader=dens-kc-group__header
kcInputClassRadio=dens-choice
kcInputClassRadioInput=dens-choice__input
kcInputClassRadioLabel=dens-choice__label
kcInputClassCheckbox=dens-choice
kcInputClassCheckboxInput=dens-choice__input
kcInputClassCheckboxLabel=dens-choice__label
kcCheckClass=dens-check
kcCheckInputClass=dens-check__input
kcCheckLabelClass=dens-check__label
kcCheckboxInputClass=dens-check__input
