parent=keycloak
import=common/keycloak

styles=css/styles.css
scripts=js/app.js
locales=it,en

densBackToSelectionUrl=https://dens.dev.numenconsulting.it/loginselector
densShowDemoCredentials=false

densBrandIcon=img/icon-brand.svg
densEmailIcon=img/icon-email.svg
densLockIcon=img/icon-lock.svg
