parent=keycloak
import=common/keycloak

styles=css/login.css css/styles.css
scripts=js/app.js
locales=it,en

densBackToSelectionUrl=https://app.dens.studio
densShowDemoCredentials=true
densDemoEmail=admin@dens.studio
densDemoPassword=admin123

densBrandIcon=img/icon-brand.svg
densEmailIcon=img/icon-email.svg
densLockIcon=img/icon-lock.svg
